### ISSUE TITLE
mouse problem with tumb buttons

### ISSUE THREAD

**Issue by Micha-Btz** [xLAva/JediAcademyLinux#12]
hi,

my mouse has on the side two buttons for the thumb. 
in the game only one i can use but both works.
![Uploading 2014-01-04-201305_1680x1050_scrot.png . . .]()

And the buttons is displayed as point, see the first "Schub".
I have found the thread bei Jedi Outcast, but this solution does't help, because the lib is missing.
------- sound initialization -------
dlopen() failed on libXxf86dga.so
but installed
root@sysiphus:/home/mdomann# dpkg -l|grep libxxf86dga*
ii  libxxf86dga-dev:amd64                                       2:1.1.4-1                          amd64        X11 Direct Graphics Access extension library (development headers)
ii  libxxf86dga1:amd64                                          2:1.1.4-1                          amd64        X11 Direct Graphics Access extension library
ii  libxxf86dga1:i386                                           2:1.1.4-1                          i386         X11 Direct Graphics Access extension library

any suggestion?
thanks
Micha

**Comment by xLAva** [comment]
hi!
Dga has nothing to do with the button support - at the moment only 3 buttons are supported.
It's on my todo list but I was quit busy the last couple of month.

**Comment by Micha-Btz** [comment]
ah, ok. would be great if you can add it.

**Comment by xLAva** [comment]
Support for up to 5 mouse buttons added.
