### ISSUE TITLE
OculusDK2 Everything is too small

### ISSUE THREAD

**Issue by rubenschwarzwald** [xLAva/JediAcademyLinux#14]
This issue is in regard with the HmdSupportDK2 tree.

Everything in the game looks like it is about 50% of the size it should be.
I think that means that the cameras are to far apart.

**Comment by xLAva** [comment]
Yes, this is still a problem.

The whole scaling of the game is an issue. The Oculus SDK works with meters as default unit, but the original Quake3 engine uses something completely different (not even feet or any other default unit), or at least I haven't found out yet.

What I found is a rough calculation from Q3 engine units to meters, but I think the world scale was changed for Jedi Academy.

I'm not happy with the current setting, but it was the best solution I could come up with for the moment. Other solution looked better, but had a strange position tracking feeling to it.

Thx for the report. At least I'm not the only one feeling that the world looks too small. It's a bit confusing changing the scaling all the time and figuring out if the new scaling value is closer to the right setting.

I will investigate this issue further.

**Comment by rubenschwarzwald** [comment]
Ok, I didn't find alist of known issues anywhere, which is why I posted it.

Otherwise great work so far!
I really hope you also make an oculus vErsion of Outcast, it is the better of the two games if you ask me.

**Comment by xLAva** [comment]
I just released a new version with changed world scale.
Check it out. I hope it is right scale.

**Comment by rubenschwarzwald** [comment]
Still seems to small. I think it is better, but not quite there yet.

Also I noticed that some cutscenes(the prerendered ones) do have headtracking while others don't. Any reason for that?

**Comment by xLAva** [comment]
I was not sure if it was still to small - it looked a bit too small to me, but it was not a dummy value but a correct calculation: inch to meter
I found out that the used Q3 engine used inch as ingame unit. This is why I used the value.
Another one was double in size, but it look too big for me, but to be honest I'm just not sure what is correct anymore.

Maybe I can give you a build with the other scaling factor if you want?

About the cutscene stuff:
Are you maybe talking about the loading screen?
The engine blocks rendering during loading, so no headtracking is possible without huge delays (multiple seconds)

**Comment by rubenschwarzwald** [comment]
Sure I can try it if you make another version. I would say about 1.5X what we currently have might be right.

With cut scenes I mean the pre-rendered videos. 

If you start a new game you get the Star Wars Scroll text, which is fine and has headtracking, then after a short in-game rendered sequence in the shuttle there is another cutscene of the shuttle going down and that cutscene for some reason has no head tracking. At least it didn't in the one time I tried it.

**Comment by xLAva** [comment]
I will try to build some test binaries for you this week.
Maybe one with 1.5x and one with 2.0x scaling.

I also created a new issue for the cut scene headtracking #15

**Comment by xLAva** [comment]
I made two builds for you to test out, one with 1.5x and one with 2.0x scaling.
[jahmd-scalefactor-1.5.zip](https://github.com/xLAva/JediAcademyLinux/files/96635/jahmd-scalefactor-1.5.zip)
[jahmd-scalefactor-2.0.zip](https://github.com/xLAva/JediAcademyLinux/files/96634/jahmd-scalefactor-2.0.zip)

**Comment by rubenschwarzwald** [comment]
Just tested both of them. I think either seem fine but I would probably prefer the 2x scale. They definetly don't look like small puppets or children in either anymore.

**Comment by xLAva** [comment]
Thx for testing.
I will integrate the 2x scaling for the next build.

**Comment by xLAva** [comment]
Fixed in VR-v3.1.0
(543bd066060671868a7cda0b0ed54abb1412d7b5)
