### ISSUE TITLE
Cutscene Headtracking missing

### ISSUE THREAD

**Issue by xLAva** [xLAva/JediAcademyLinux#15]
Some Video Cutscene have headtracking, some are missing headtracking

**Comment by xLAva** [comment]
According to rubenschwarzwald:

[...]
If you start a new game you get the Star Wars Scroll text, which is fine and has headtracking, then after a short in-game rendered sequence in the shuttle there is another cutscene of the shuttle going down and that cutscene for some reason has no head tracking. At least it didn't in the one time I tried it.
[...]

**Comment by hectorgrey** [comment]
Some cut scenes are prerendered; is it those that don't have head
tracking?  That would make sense, since they're just video files...

**Comment by xLAva** [comment]
With the new OculusSDK 0.8 the Videos should be rendered on a quad placed in worldspace, so it should not be pinned to your head anymore.
And there is a bug that some videos are still pinned and some are handled correctly.

**Comment by xLAva** [comment]
I build the game with 2 different scaling factors:
- 1.5
- 2.0

Please test it out. Thx!

[jahmd-scalefactor-1.5.zip](https://github.com/xLAva/JediAcademyLinux/files/93308/jahmd-scalefactor-1.5.zip)
[jahmd-scalefactor-2.0.zip](https://github.com/xLAva/JediAcademyLinux/files/93309/jahmd-scalefactor-2.0.zip)

**Comment by rubenschwarzwald** [comment]
Just tested them and cut-scenes(at least the ones during the intro, don't know if there are any others) all work fine now!

**Comment by xLAva** [comment]
Nice. I will make a new build this weekend.
