### ISSUE TITLE
No multiplayer ?

### ISSUE THREAD

**Issue by Mr5quid** [xLAva/JediAcademyLinux#16]
Hi,

I have the GOG version of Jedi Academy and I wanted to play it on Linux. It seems to me that all the multiplayer components of the game are present in the source code yet I don't have the multiplayer menu in the game at all.

I did not build it myself (although I tried but got an include file missing error), I downloaded the 3.0 release and put it in the GameData folder as required. It launches and plays fine there's just no multiplayer.

Is this normal ?

**Comment by xLAva** [comment]
Hi!

The multiplayer part is actually a separated executable, which uses some shared code from the single player version and some multiplayer code parts.

I only ported the single player part to Linux. So the multiplayer is not working with my port.

But you can check out the OpenJK project. They also ported Jedi Academy to Linux and I think they did it for the multiplayer part as well. 
As far as I know they also fixed some issues and improved the game. My port is as original as possible (with all the original bugs).

Here is the link to OpenJK: https://jkhub.org/topic/2220-frequently-asked-questions/

**Comment by Mr5quid** [comment]
Thanks a lot for this insanely fast answer. I'm looking into the OpenJK project.

I just learned yesterday that the source code of Jedi Academy has been released and I'm thrilled to see so many projects articulated around it.
