### ISSUE TITLE
Linux - game not start

### ISSUE THREAD

**Issue by Micha-Btz** [xLAva/JediAcademyLinux#17]
Hi there,
I would play this good old thing once again but the game doesn't start.

```
media/games/academy$ ./jasp
(internal)JA: v1.0.1.0 linux-i386 Jan  7 2014
Initialising zone memory .....
----- FS_Startup -----
Current search path:
/home/mdomann/.jk3-ja/base
./base

----------------------
0 files in pk3 files

Running in restricted demo mode.

----- FS_Startup -----
Current search path:
/home/mdomann/.jk3-ja/demo
./demo

----------------------
0 files in pk3 files
Error: Couldn't load default.cfg
```
I'm sure it has been worked. Any Idea what can I do? I'm using Debian Sid.
Does it matter that I don't have a Oculus Rift device? Which version is the best to use?
TIA Micha

**Comment by xLAva** [comment]
Hi Micha!
It looks like the game does not fine the original Jedi Academy resources.
Did you follow the instructions and place the Linux executable alongside the Windows executable in the Jedi Academy installation folder?

There should be a sub folder named "base" where the executable tries to load the resources.

**Comment by Micha-Btz** [comment]
arg, the problem is, that the install has created Base and linux's looks for base. a simple rename fix the problem.can you just tell me which is the best version to use without Oculus Rift device?

**Comment by AlexCS1337** [comment]
https://github.com/JACoders/OpenJK for jka without oculus rift

**Comment by xLAva** [comment]
The newest Oculus Rift Version also works fine without the Rift. If no VR device is detected it just runs in normal Desktop mode.

Thx for the feedback on the folder name issue. I will take a look at it, so it works with all cases.
