### ISSUE TITLE
HUD separation too far apart - shows as double in Rift CV1

### ISSUE THREAD

**Issue by baggyg** [xLAva/JediAcademyLinux#18]
Hi, 
I am not sure if this project is still maintained. I originally tried this game on the DK2, and wanted to give it another whirl now I have a CV1. I reinstalled, downloaded the latest release and started the game. Unfortunately the in-game HUD (radar) seems to have the wrong separation. Its too wide apart so you see it doubly in the headset and gives you a headache trying to look at it. 

Is there a console command or similar I can use to fix this?

**Comment by xLAva** [comment]
I will check it out. I thought I fixed this ages ago. Did you use the latest release?

**Comment by xLAva** [comment]
I found it. I fixed it in code but never made a new binary.
I will do that right now.

**Comment by baggyg** [comment]
Ah perfect, glad it wasn't too difficult to find. Let me know when the binary is there and I'll retest. Awesome that you still respond on this project.

**Comment by xLAva** [comment]
New version is released: https://github.com/xLAva/JediAcademyLinux/releases/tag/VR-v3.1.1
I'm glad that there are still people out there interested in this project :-)

**Comment by baggyg** [comment]
That looks perfect - thanks!
