### ISSUE TITLE
(Not so much an issue but more asking for help) Does anyone know how to get mods to work

### ISSUE THREAD

**Issue by Amredd** [xLAva/JediAcademyLinux#23]
we and my brothers have been trying to get mods like escape yavin 4, ultimate academy, and other SP mods to work but none of the mods work.
What confuses me is that I've gotten mods like eve of redemption to work.

please help.

**Comment by xLAva** [comment]
Unfortunately most mods will never work.
As far as I understand it, a lot of mods patch the original game by overriding content in certain memory positions of the original binary.
Even a small change in the binary could break them.

This project of course has a lot of changes, a new compiler, so the binary changed a lot.

So sadly, mods that patch the game by memory hooks/overrides will never work.
