### ISSUE TITLE
level vjun1 crashes when load game

### ISSUE THREAD

**Issue by jarenere** [xLAva/JediAcademyLinux#6]
level vjun1 often crashes when I load a game ( checkpoint or quick load) and I have to restart the level
log:
http://pastebin.com/j9RuHd9G

config and saves (checkpoint and quick save crash)
https://www.dropbox.com/s/kmh2i6a53qjq0ru/config%26saves.tar.gz

PS: I have not had any problems with jedikinght2 (I played all levels), the only problem, the shadows as I already discuss you. In academy is also the problem of shadows, as I expected, xD

**Comment by xLAva** [comment]
Thx for the report.
I can reproduce the crash with your savegames. I'll check this out as soon as possible.
